module Test

import Data.Bytes
import Data.Word.Word8

testStrict  : IO ()
testLazy    : IO ()
testBuilder : IO ()

main : IO ()
main = do
  testStrict
  testLazy
  testBuilder


-- tail : IO ()
-- tail = try all the tails here on various generated Bytes
-- 
-- test_tail : Bool
-- test_tail = tail [1,2,3] == [2,3]
-- 
-- test_tail' : Bool
-- test_tail' = tail' [1,2,3] == [2,3]

