module Test

import Data.Bytes
import Data.Word.Word8

import Test.LazyTest

testStrict  : IO ()
testLazy    : IO ()
testBuilder : IO ()

main : IO ()
main = do
  -- testStrict
  -- testLazy
  -- testBuilder
  printLn "Testing lazy file IO:" *> lazyIOTest



-- tail : IO ()
-- tail = try all the tails here on various generated Bytes
-- 
-- test_tail : Bool
-- test_tail = tail [1,2,3] == [2,3]
-- 
-- test_tail' : Bool
-- test_tail' = tail' [1,2,3] == [2,3]

